language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  - COMPOSER="5.8"
  - COMPOSER=""

before_script:
  - test ${COMPOSER_FLAGS} && cp composer-${COMPOSER_FLAGS}.json composer.json
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
